server:
  port: 8082
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: LocationService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/weatherapp
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

        
resilience4j:
  circuitbreaker:
    instances:
       ISE:
          register-health-indicator: true
          event-consumer-buffer-size: 10
          failure-rate-threshold: 10
          minimum-number-of-calls: 2
          automatic-transition-from-open-to-half-open-enabled: true
          wait-duration-in-open-state: 5s
          permitted-number-of-calls-in-half-open-state: 1
          sliding-window-size: 10
          sliding-window-type: count-based
          
eureka:
  instance:
    appname: location-service
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.4:8762/eureka/


  
        
