server:
  port: 8989
spring:
  zipkin:
    base-url: http://localhost:9411/zipkin/ 
  application:
    name: Weather-Gateway-Service
  cloud:
    gateway:
      routes: 
      - id: location-service
        uri: lb://LocationService
        predicates:
        - Path=/location/**
      - id: weather-details-service
        uri: lb://WEATHERSERVICE
        predicates:
        - Path=/weather/**    
      globalcors:
        cors-configurations:
          '[*]':
            allowedOrigins: "*"
            allowedMethods: "*"
        
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.1.4:8762/eureka/
    