server:
  port: 8081
spring:
  boot:
    admin:
      client:
        url: http://localhost:8093/
  zipkin:
    base-url: http://localhost:9411/
  mvc:
    pathmatch:
       matching-strategy: ant-path-matcher
  application:
    name: WeatherService
eureka:
  instance:
    appname: WeatherService
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.4:8762/eureka/ 
